DATASET:
  SOURCE: Inner
  DIR: dataset
  TRAIN_DIR:  
  - '/Users/timshieh/Documents/Reconition_Github/E.SunBankOCR/train_data/train'
  # - '/Users/timshieh/Documents/Reconition_Github/E.SunBankOCR/train_data/patch'

  VALID_DIR:  
  - '/Users/timshieh/Documents/Reconition_Github/E.SunBankOCR/train_data/valid'
  TEST_DIR:   
  - '/Users/timshieh/Documents/Reconition_Github/E.SunBankOCR/train_data/test'

  IMAGE_HEIGHT: 128 #67
  IMAGE_WIDTH: 128 #120
  CHANNELS: 3

MODEL:
  BACKBONE: resnet18 #resnet18 resnet34 resnet50 resnet101 resnet152
  BACKBONE_OUTPUT_SIZE: 512
  NUM_CLASSES: 800

TRAINING:
  EPOCH     : 20
  BATCH_SIZE: 32        # Batch size.
  LEARNING_RATE: 0.0005 # Learning rate. 0.001
  SAVE_MODEL_DIR: '/Users/timshieh/Documents/Reconition_Github/E.SunBankOCR/resnet18_office_data/model'  #/Users/timshieh/Documents/HandWritingCategory/HandWritingCategory/saved_model/resnet34_saved_model/model"  "/Users/timshieh/Documents/HandWritingCategory/HandWritingCategory/saved_model/resnet18_saved_model/model"
  LOSS: sparse_category_loss #"balance_loss"  # sparse_category_loss 
  SAVE_TIMES: 5
  RETRAIN_MODEL_DIR: '/Users/timshieh/Documents/Reconition_Github/E.SunBankOCR/resnet18_new/model'

TESTING:
  BATCH_SIZE: 100        # Batch size.